### ISSUE TITLE
Crash on clicking play on project

### ISSUE THREAD

**Issue by TheCyberWarlock** [zodywoolsey/bark#1]
"Attempt to call function 'file_exists' in base 'nuyll instance' on a null instance."

Line 128 in vector.gd, "	if file.file_exists("user://user.data"):" is where the debugger is pointing me after the crash.

Also, hi! I'm poking around in the codebase for fun, looks like you've done a lot of work so far! I'm sure it's a newb mistake on my end, not sure what user://user.data is, but it must be something you've created locally?

**Comment by zodiepupper** [comment]
What version of Godot are you using? The user://user.data is the location of the user data. Godot has pre-configured locations where it will put the res:// and user:// directories, so it should just be mapped to your %appdata%/godot/app_userdata/bark on windows. I'll test it and see what's happening.

It could be because the last time I touched this version of the project I was working on user caching and I think I didn't quite check everything yet, so I might have made it expect an existing user login by accident.

**Comment by zodiepupper** [comment]
Ok, I'm about to push a commit that will fix it. I had a faulty check for whether the file existed. I need to make the user login cache loading more robust at some point, but I've been primarily working on the barkvr repo lately.

Also, please note that this is kinda still just in the "me trying to figure out what I need to get things working" phase, so the app doesn't display messages properly yet lol. If you click on a room after login, it will open my json viewer and let you browse the room state data. You can expect messages and better formatting very very soon as I have a lot of changes on my local for the VR client.
